---

- name: Install git
  apt:
    name: git
    update_cache: yes

- name: Install Memcached
  apt:
    name: memcached

- name: Ensure Memcached is started and set to run on startup.
  service:
    name: memcached
    state: started
    enabled: yes

- name: Clone git repo
  become_user: ubuntu
  git:
    repo: https://github.com/dnsanalytics/scripts.git
    dest: "{{ repo_location }}"
    accept_hostkey: yes

- name: Add Node.js PPA
  shell: 'curl --silent --location https://deb.nodesource.com/setup_"{{ nodejs_version }}" | bash -'

- name: Install Node.js
  apt:
    name: nodejs
    update_cache: yes
    state: latest

- name: npm Update
  npm:
    name: npm
    global: yes
    state: latest
    registry: https://registry.npmjs.org

- name: Install pm2
  npm:
    name: pm2
    global: yes

- name: pm2 Start Up settings
  shell: pm2 startup
  become_user: ubuntu

- name: Install REST Dependencies
  become_user: ubuntu
  npm:
    path: "{{ server_location }}"

- name: Start API
  shell: pm2 start server.js -i 0 --watch --name lookup-api
  become_user: ubuntu
  args:
    chdir: "{{ server_location }}"

- name: Save pm2 settings for start on reboot
  shell: pm2 save
  become_user: ubuntu
